// Alle drankspelletjes + uitleg. Research is een startpunt — pas gerust aan!
const GAMES = [
  {
    id: "kingsen",
    naam: "Kingsen",
    emoji: "👑",
    tagline: "De koning van alle kaartspellen. Elke kaart = een regel.",
    categorie: ["Kaarten"],
    spelers: "4-12",
    heat: 4,
    nodig: ["1 kaartspel", "Een kring met glazen", "Een grote beker/pot in het midden"],
    regels: [
      "Leg alle kaarten verdeeld en met de achterkant naar boven in een cirkel rond een leeg glas of pot (de 'King's Cup').",
      "Om de beurt trekt iedereen een kaart en voert de bijbehorende regel uit.",
      "A = Waterval: iedereen begint te drinken, je mag pas stoppen als de persoon rechts van je stopt.",
      "2 = Jij: wijs iemand aan die moet drinken.",
      "3 = Ik: jijzelf drinkt.",
      "4 = Vloer: laatste die de vloer aanraakt drinkt.",
      "5 = Man/Jongens: alle mannen drinken.",
      "6 = Vrouw/Dames: alle vrouwen drinken.",
      "7 = Hemel: laatste die een hand omhoog steekt drinkt.",
      "8 = Maatje: kies een drinkmaatje, jullie drinken samen de rest van het spel.",
      "9 = Rijm: noem een woord, de kring gaat rond met rijmwoorden tot iemand hapert.",
      "10 = Categorie: noem een categorie (bv. automerken), om de beurt een woord noemen tot iemand vastloopt.",
      "Boer = Nieuwe regel: verzin een regel die de rest van het spel geldt.",
      "Vrouw = Categorie/Quizmaster: zelfde als 10, of stel vragen — wie antwoordt drinkt.",
      "Koning = Giet een scheut van je eigen drankje in de King's Cup. De 4e koning drinkt de hele cup leeg!",
    ],
    tips: [
      "Spreek vooraf af of Boer 'Regel' of iets anders betekent — er zijn tientallen huisregels.",
      "Zet een zoete mix in de King's Cup, de laatste koning zal je dankbaar zijn.",
    ],
  },
  {
    id: "mexxen",
    naam: "Mexxen (Mexicaans)",
    emoji: "🎲",
    tagline: "Bluf, bedrieg en dobbel je een weg naar de bodem van je glas.",
    categorie: ["Dobbelen", "Bluf"],
    spelers: "3-8",
    heat: 4,
    nodig: ["2 dobbelstenen", "Een bekertje om te schudden"],
    regels: [
      "Iedereen gooit om de beurt met een afgeschermd bekertje zodat niemand de worp ziet.",
      "Je bekijkt zelf je worp en zegt een waarde hardop — dit mag liegen zijn (bluffen).",
      "De hoogste 'worp' is 21 (Mexicaan: een 2 en een 1). Daarna dalen de dubbels (66, 55, 44...), gevolgd door gewone combinaties van hoog naar laag.",
      "De volgende speler mag geloven en doorgooien, of twijfelen en het bekertje omdraaien om te checken.",
      "Blijkt de vorige speler te hebben gelogen (lagere worp gegooid dan gezegd)? Die drinkt. Klopte het wél? Dan drinkt de twijfelaar.",
      "Wie de laagste worp gooit (of betrapt wordt op een te lage bluf) neemt een slok.",
    ],
    tips: [
      "Een goede pokerface is goud waard.",
      "Durf je het bekertje nooit te checken, dan win je nooit — durf je het altijd, dan lieg je nooit ongestraft.",
    ],
  },
  {
    id: "juffen",
    naam: "Juffen (en varianten)",
    emoji: "🔢",
    tagline: "Tellen tot je in de war raakt. Bij 7 zeg je 'juf'!",
    categorie: ["Tellen", "Reflex"],
    spelers: "3-15",
    heat: 3,
    nodig: ["Niks! Alleen je hersenen (en die worden steeds slechter)"],
    regels: [
      "Ga in een kring zitten of staan. Begin te tellen: speler 1 zegt '1', speler 2 zegt '2', enzovoort.",
      "Bij elk getal met een 7 erin (7, 17, 27...) of elk veelvoud van 7 (7, 14, 21, 28...) zeg je 'juf' in plaats van het getal.",
      "Zeg je per ongeluk het getal, of hapert je te lang? Dan drink je en begint het tellen weer bij 1.",
      "Variant 'Omkeren': zeg ook 'juf' bij dubbele cijfers (11, 22, 33...) — bij een 'juf' draait de telrichting om.",
      "Variant 'Romeins Juffen': tel in Romeinse cijfers (I, II, III, IV...) met dezelfde juf-regel.",
      "Variant 'Verzin je woord': vervang 'juf' door een zelfgekozen woord voor extra verwarring.",
    ],
    tips: [
      "Hoe verder je komt, hoe stiller en geconcentreerder de tafel wordt — heerlijk om te saboteren met een grapje.",
    ],
  },
  {
    id: "senor-trois",
    naam: "Señor Trois",
    emoji: "🤠",
    tagline: "Regionale dobbelvariant rond het getal drie — mis 'm niet!",
    categorie: ["Dobbelen"],
    spelers: "3-10",
    heat: 3,
    nodig: ["2 dobbelstenen"],
    regels: [
      "Dit is een regionale variant (leg je eigen huisregels vast, versies verschillen per groep/kroeg!).",
      "Ga om de beurt met twee dobbelstenen gooien. Gooi je een 3 op één van de stenen? Roep dan luid 'Señor Trois!' voordat de volgende speler gooit.",
      "Ben je te laat of vergeet je het te roepen? Dan drink je.",
      "Gooi je een dubbele 3 (3-3)? Dan wijs je twee spelers aan die allebei moeten drinken.",
      "Gooi je in totaal 3 punten (bv. 1+2)? Dan drink je zelf een korte 'siësta-slok'.",
    ],
    tips: [
      "Dit spel leeft vooral als studenten-/vriendengroepvariant — de details verschillen overal. Pas 'm gerust aan naar jouw eigen versie.",
    ],
  },
  {
    id: "aristoteles-telspel",
    naam: "Aristoteles Telspel",
    emoji: "🏛️",
    tagline: "Filosofisch tellen tot 12, met elke ronde een nieuwe eigen regel.",
    categorie: ["Tellen"],
    spelers: "4-12",
    heat: 4,
    nodig: ["Goed geheugen", "Genoeg drank voor als het misgaat"],
    regels: [
      "Ga in een kring zitten. Speler 1 telt '1', speler 2 telt '2', tot je bij 12 komt.",
      "In plaats van '12' te zeggen, verzint de speler die aan de beurt is een eigen regel die vanaf nu geldt (bv. 'niet meer wijzen' of 'links drinken met je rechterhand').",
      "Tel opnieuw vanaf 1, met de nieuwe regel erbij.",
      "Elke volgende 'ronde van 12' levert weer een nieuwe regel op, die zich opstapelt bovenop de vorige.",
      "Overtreedt iemand een regel (of verspreekt zich met tellen)? Diegene drinkt en het tellen begint weer bij 1 — met alle regels nog intact.",
    ],
    tips: [
      "Na een paar rondes zijn er zoveel regels dat niemand ze nog allemaal kan volgen — dát is het hele punt.",
    ],
  },
  {
    id: "aristoteles-corpsenspel",
    naam: "Aristoteles Corpsenspel",
    emoji: "🎩",
    tagline: "Strenge commando's, rangen en standjes — heel de tafel doet mee.",
    categorie: ["Commando's"],
    spelers: "5-15",
    heat: 4,
    nodig: ["Een 'praeses' (spelleider) om de beurt"],
    regels: [
      "Eén speler is de 'Praeses' (leider) voor deze ronde en geeft commando's die iedereen direct moet uitvoeren.",
      "Klassieke commando's: 'Ex!' (leeg je glas), 'Onder de tafel!' (iedereen duikt weg), 'Handen op tafel!', 'Stilte!'.",
      "Wie het laatst reageert of de opdracht verkeerd uitvoert, moet drinken.",
      "Na een paar commando's wisselt de rol van Praeses naar de volgende speler (of naar wie het laatst dronk).",
      "Verzin gerust eigen commando's — hoe absurder, hoe grappiger.",
    ],
    tips: [
      "Dit spel leunt op studentencorps-tradities; hou het luchtig en dwing niemand méér te drinken dan die wil.",
    ],
  },
  {
    id: "lepelen",
    naam: "Lepelen (Spoons)",
    emoji: "🥄",
    tagline: "Verzamel vier gelijke kaarten en gráái die lepel voor het te laat is.",
    categorie: ["Kaarten", "Reflex"],
    spelers: "4-8",
    heat: 2,
    nodig: ["1 kaartspel", "Lepels: 1 minder dan het aantal spelers"],
    regels: [
      "Leg lepels in het midden van de tafel — altijd één minder dan er spelers zijn.",
      "Iedereen krijgt 4 kaarten. De rest van het spel ligt als stapel bij de gever.",
      "De gever pakt telkens 1 kaart van de stapel, kijkt of die nuttig is en legt er 1 door aan de volgende speler — zo gaat het snel rond.",
      "Doel: als eerste 4 kaarten van dezelfde waarde verzamelen (bv. vier azen).",
      "Heb je vier gelijke kaarten? Pak stiekem een lepel! Zodra iemand een lepel pakt, mag iedereen grissen.",
      "Wie zonder lepel achterblijft, drinkt.",
    ],
    tips: [
      "Wees subtiel als je vier gelijke kaarten hebt — te snel grissen verraadt je aan de tafel.",
    ],
  },
  {
    id: "chinees-of-japans",
    naam: "Chinees of Japans",
    emoji: "🈴",
    tagline: "Razendsnel handspel: gok goed of gok fout, en drink.",
    categorie: ["Reflex"],
    spelers: "2 (of meerdere 1-op-1 duels)",
    heat: 2,
    nodig: ["Alleen je handen"],
    regels: [
      "Twee spelers staan tegenover elkaar met beide handen achter hun rug.",
      "Op de telling '1, 2, 3' brengen beiden tegelijk beide handen naar voren, elke hand met de palm naar boven of naar beneden.",
      "Tel het totaal aantal 'open' handen (palm omhoog) van beide spelers samen.",
      "Vooraf kiest elke speler stiekem 'Chinees' (even aantal) of 'Japans' (oneven aantal).",
      "Klopt jouw voorspelling met het totaal? Dan wijs je de ander aan om te drinken. Klopt die niet, drink je zelf.",
    ],
    tips: [
      "Ideaal als snel 1-op-1 duel tussen twee grote drankspellen door.",
    ],
  },
  {
    id: "zap-de-asian",
    naam: "Zap de Asian",
    emoji: "⚡",
    tagline: "Wijs, tik en reageer — wie te laat is, drinkt.",
    categorie: ["Reflex"],
    spelers: "4-12",
    heat: 3,
    nodig: ["Snelle handen"],
    regels: [
      "Iedereen zit in een kring. Eén speler begint met 'Zap!' en wijst met beide handen (als een pistooltje) naar een andere speler.",
      "Die speler moet binnen 1 seconde reageren: óf 'zap' terugsturen naar iemand anders, óf bukken terwijl de buren links en rechts elkaar 'zappen'.",
      "Reageer je fout, te langzaam, of zap je iemand die net gezapt is terug? Dan drink je.",
      "Voeg naar smaak extra bewegingen toe (bv. 'reload' = allebei je handen herladen voor je opnieuw mag zappen).",
    ],
    tips: [
      "Bouw het tempo langzaam op — na een paar rondes gaat dit spel razendsnel.",
    ],
  },
  {
    id: "vikingen",
    naam: "Vikingen",
    emoji: "🛶",
    tagline: "Word Viking, Roeier of Zee — en blijf goed opletten.",
    categorie: ["Rollen", "Commando's"],
    spelers: "5-15",
    heat: 3,
    nodig: ["Ruimte om te bewegen"],
    regels: [
      "Eén speler is de Viking: die maakt met de vingers hoorns op het hoofd en roept vikinggeluiden ('Uh, uh, uh!').",
      "De twee spelers links en rechts van de Viking zijn de Roeiers: zij maken roeibewegingen en roepen 'Roei, roei, roei!'.",
      "Alle overige spelers zijn de Zee: zij maken golfbewegingen met hun armen en roepen 'Zee, zee, zee!'.",
      "De Viking wijst plotseling met gestrekte armen naar een andere speler — die wordt nu de nieuwe Viking, en alle rollen rond die persoon wisselen mee.",
      "Maakt iemand de verkeerde beweging, het verkeerde geluid, of reageert die te laat? Die persoon drinkt.",
    ],
    tips: [
      "Vaak gespeeld als losse ronde binnen Kingsen, maar werkt ook prima los.",
    ],
  },
  {
    id: "thumbmaster",
    naam: "Thumbmaster",
    emoji: "👍",
    tagline: "Stiekem je duim op tafel leggen — de laatste drinkt.",
    categorie: ["Commando's", "Kaarten"],
    spelers: "4-12",
    heat: 2,
    nodig: ["Een tafel"],
    regels: [
      "Eén speler wordt de Thumbmaster (bv. via een kaart uit Kingsen, of gewoon om de beurt).",
      "Op willekeurige momenten, zonder waarschuwing, legt de Thumbmaster stiekem zijn/haar duim op tafel.",
      "Zodra iemand het merkt, moet die ook snel zijn duim op tafel leggen — en zo iedereen achter elkaar.",
      "De laatste speler die zijn duim op tafel legt, moet drinken.",
      "De Thumbmaster blijft dit doen tot een nieuwe Thumbmaster wordt aangewezen.",
    ],
    tips: [
      "Werkt geweldig als sluimerende regel naast een ander hoofdspel — niemand verwacht het.",
    ],
  },
  {
    id: "snakeeyes",
    naam: "Snake Eyes",
    emoji: "🐍",
    tagline: "Oogcontact met de Snake Eyes-houder? Dan drink jij.",
    categorie: ["Commando's", "Kaarten"],
    spelers: "4-15",
    heat: 2,
    nodig: ["Ogen (die je verder juist wíl vermijden)"],
    regels: [
      "Eén speler krijgt de titel Snake Eyes (bv. via een kaart uit Kingsen).",
      "Vanaf nu geldt: maakt iemand op wélk moment dan ook oogcontact met de Snake Eyes-houder, dan moet die persoon drinken.",
      "De Snake Eyes-houder mag dus stiekem proberen oogcontact uit te lokken, de hele avond door.",
      "Wordt een nieuwe Snake Eyes-kaart getrokken? Dan verhuist de titel (en dus ook de macht) naar die nieuwe speler.",
    ],
    tips: [
      "Combineer met Thumbmaster voor twee sluimerende regels tegelijk — dubbel zo verraderlijk.",
    ],
  },
  {
    id: "categorie",
    naam: "Categorie",
    emoji: "📋",
    tagline: "Noem om de beurt iets uit een categorie, tot iemand vastloopt.",
    categorie: ["Woordspel"],
    spelers: "3-12",
    heat: 2,
    nodig: ["Kennis van willekeurige onderwerpen"],
    regels: [
      "Eén speler kiest een categorie, bijvoorbeeld 'automerken', 'Disney-films' of 'dingen die je in de koelkast vindt'.",
      "Om de beurt (met de klok mee) noemt iedereen één voorbeeld uit die categorie.",
      "Herhalingen zijn niet toegestaan — noem je iets dat al gezegd is, dan drink je.",
      "Kun je niks (meer) bedenken binnen een paar seconden? Dan drink je en start een nieuwe ronde met een nieuwe categorie.",
    ],
    tips: [
      "Kies expres een lastige categorie voor je vijand rechts van je.",
    ],
  },
  {
    id: "dierenslang",
    naam: "Dierenslang",
    emoji: "🐍🦁",
    tagline: "Bouw samen een steeds langere ketting van dieren en geluiden.",
    categorie: ["Geheugenspel"],
    spelers: "4-15",
    heat: 3,
    nodig: ["Een goed geheugen en durf om dierengeluiden te maken"],
    regels: [
      "Speler 1 noemt een dier en maakt het bijbehorende geluid/beweging, bv. 'Aap 🙉' met een aapgeluid.",
      "Speler 2 herhaalt dier 1 (geluid + beweging) en voegt er een nieuw dier aan toe.",
      "Speler 3 herhaalt dier 1 én 2, en voegt een derde toe — zo groeit de 'slang' elke beurt.",
      "Vergeet je een dier, verwissel je de volgorde, of doe je het verkeerde geluid? Dan drink je en begint de slang weer bij nul.",
    ],
    tips: [
      "Kies opvallende, fysieke dieren (olifant, kip, slang) — makkelijker te onthouden dan namen alleen.",
    ],
  },
  {
    id: "chinees-plof",
    naam: "Chinees Plof",
    emoji: "👏",
    tagline: "Klap het ritme door de kring tot iemand de 'plof' verpest.",
    categorie: ["Reflex", "Ritme"],
    spelers: "5-15",
    heat: 3,
    nodig: ["Ritmegevoel"],
    regels: [
      "Ga in een kring staan of zitten. Samen klap je een vast ritme: op-dij, op-dij, klap, klap.",
      "Op het ritme 'stuurt' iedere speler op zijn beurt de beweging door naar links of rechts (bv. met een hand-'plof'-gebaar naar de buurman).",
      "Wie de plof ontvangt, moet binnen het ritme reageren en 'm doorsturen — mis je het ritme of de richting, dan drink je.",
      "Maak het lastiger door een 'terugkaats'-gebaar toe te voegen dat de plof omdraait.",
    ],
    tips: [
      "Begin langzaam met het ritme, het tempo loopt vanzelf op naarmate iedereen het onder de knie krijgt.",
    ],
  },
  {
    id: "mosselmannen",
    naam: "Mosselmannen",
    emoji: "🎵🦪",
    tagline: "Zing, rijm en verzin door tot het rijmwoord op is.",
    categorie: ["Zingen", "Woordspel"],
    spelers: "4-15",
    heat: 3,
    nodig: ["Zangstem (kwaliteit optioneel)"],
    regels: [
      "De hele tafel zingt samen: 'Zeg ken jij de Mosselman, de Mosselman, de Mosselman? Zeg ken jij de Mosselman, die woont in Zandvoort aan Zee?'",
      "De eerste speler verzint direct een nieuwe, rijmende zin die aansluit op 'Zee'.",
      "De hele tafel zingt het versje opnieuw, waarna de volgende speler een nieuwe regel verzint die rijmt op de vorige.",
      "Kun je geen rijmwoord (meer) bedenken, gebruik je een niet-bestaand woord, of herhaal je een eerder gebruikt rijmwoord? Dan drink je.",
      "Bij twijfel of iets rijmt of een woord bestaat, beslist de tafel democratisch.",
    ],
    tips: [
      "Hoe verder het spel vordert, hoe schaarser de rijmwoorden — bewaar je beste rijm niet te vroeg.",
    ],
  },
  {
    id: "proletenspel",
    naam: "Aristoteles Proletenspel",
    emoji: "🍺",
    tagline: "De instapversie: simpele regels, snel geleerd, hard gelachen.",
    categorie: ["Commando's", "Beginners"],
    spelers: "3-15",
    heat: 2,
    nodig: ["Niks — perfect voor beginners"],
    regels: [
      "De ideale opwarmer: één speler is spelleider en geeft simpele, snelle opdrachten die iedereen direct uitvoert.",
      "Basisopdrachten: 'Proost!' (klink met je buren), 'Op!' (neem een slok), 'Wissel!' (ruil van plek met iemand), 'Stil!' (niemand mag praten tot de volgende opdracht).",
      "Wie te laat, verkeerd, of helemaal niet reageert, drinkt.",
      "Na een paar minuten wisselt de rol van spelleider door naar de volgende speler.",
      "Geen ingewikkelde regels, geen strategie — puur een laagdrempelige groepswarming voor het echte werk begint.",
    ],
    tips: [
      "Perfect als eerste spel van de avond om iedereen erbij te betrekken, ook de mensen die drankspellen niet zo goed kennen.",
    ],
  },
  {
    id: "fuck-de-dealer",
    naam: "Fuck de Dealer",
    emoji: "🃏",
    tagline: "Hoger of lager gokken tegen de dealer — verlies en drink mee.",
    categorie: ["Kaarten", "Gokken"],
    spelers: "3-10",
    heat: 4,
    nodig: ["1 kaartspel"],
    regels: [
      "Eén speler is de Dealer voor deze ronde en houdt de kaartenstapel vast (met de rug naar boven).",
      "De andere spelers gokken om de beurt: wordt de volgende omgedraaide kaart hoger of lager dan de vorige?",
      "Gok je fout? Dan drink je het aantal slokken gelijk aan het verschil tussen de kaarten (of een vast aantal, spreek dit vooraf af).",
      "Gok je goed? Dan mag je zelf een aantal slokken uitdelen aan een andere speler.",
      "Is de stapel op, of heeft de Dealer een vaste reeks fout geraden gehad? Dan wordt de Dealer gewisseld.",
      "Sommige varianten: bij een verkeerde gok drinkt de Dealer zelf mee, of moet de gokker een eigen kaart drinken-per-waarde-verschil.",
    ],
    tips: [
      "Zwarte/rode gok (i.p.v. hoger/lager) is een leukere variant voor gevorderden.",
    ],
  },
  {
    id: "bussen",
    naam: "Bussen (Ride the Bus)",
    emoji: "🚌",
    tagline: "Twee fases: eerst gokken, dan de beruchte piramide van de bus.",
    categorie: ["Kaarten", "Gokken"],
    spelers: "3-8",
    heat: 5,
    nodig: ["1 kaartspel", "Geduld voor de bus-fase"],
    regels: [
      "FASE 1 — Individueel gokken: elke speler krijgt om de beurt 4 vragen over een kaart die wordt omgedraaid: Rood of zwart? Hoger of lager dan de vorige? Binnen of buiten (tussen de vorige twee)? Welk symbool (♥♦♣♠)?",
      "Bij elke foute gok drink je een slok. Na de 4 vragen is de volgende speler aan de beurt.",
      "FASE 2 — De Piramide: leg kaarten in een piramide (rij van 1 tot bv. 5). Elke speler krijgt evenveel kaarten op de hand als er rijen zijn.",
      "Draai de piramide rij voor rij om, van onder naar boven. Heeft een speler een kaart met dezelfde waarde op de hand? Dan mag die slokken uitdelen — hoe hoger de rij, hoe meer slokken.",
      "FASE 3 — De Bus: de speler(s) met de minste/meeste kaarten (spreek vooraf af) 'rijdt de bus': er wordt een nieuwe rij van 5 kaarten neergelegd en die speler moet steeds raden of de volgende hoger of lager is, van links naar rechts.",
      "Bij een foute gok in de bus begin je die rij van 5 helemaal opnieuw. Pas als alle 5 goed geraden zijn, ben je van de bus af!",
    ],
    tips: [
      "De bus-fase kan lang duren bij pech — houd de sfeer erin met aanmoedigingen (of gejoel).",
    ],
  },
  {
    id: "pyramidespel",
    naam: "Pyramidespel",
    emoji: "🔺",
    tagline: "Bouw een piramide van kaarten en deel slokken uit op waarde.",
    categorie: ["Kaarten", "Gokken"],
    spelers: "3-10",
    heat: 4,
    nodig: ["1 kaartspel"],
    regels: [
      "Bouw een piramide van kaarten met de achterkant naar boven: onderste rij 5 kaarten, dan 4, 3, 2, en 1 kaart bovenop.",
      "Deel de rest van de kaarten gelijk uit — dit zijn de handkaarten van elke speler (verborgen houden!).",
      "Draai de piramide rij voor rij om, te beginnen bij de onderste rij. Elke rij vertegenwoordigt een aantal slokken (rij 1 = 1 slok, tot de top = 5 slokken).",
      "Heb je een kaart op de hand met dezelfde waarde als de omgedraaide kaart? Leg 'm neer en wijs een speler aan die dat aantal slokken moet drinken.",
      "De aangewezen speler mag 'bluf!' roepen als die denkt dat je liegt over het hebben van die kaart — klopt het niet, dan drink jij zelf dubbel.",
      "Het spel is voorbij als de hele piramide is omgedraaid.",
    ],
    tips: [
      "Bewaar je hoge-waarde kaarten voor de top van de piramide — daar tellen ze het zwaarst.",
    ],
  },
];
